In [14]:
import pandas as pd
import duckdb
from pathlib import Path

In [16]:
data_path = Path.cwd().parent / "dev.duckdb"
conn = duckdb.connect(database=str(data_path))  
data_path

PosixPath('/workspaces/NPPES_2/dev.duckdb')

In [18]:
conn.execute("SHOW ALL TABLES").fetchdf()

,database,schema,name,column_names,column_types,temporary
0,dev,main,nppes_sammpledf,"[NPI, Entity Type Code, Replacement NPI, Emplo...","[BIGINT, DOUBLE, DOUBLE, VARCHAR, VARCHAR, VAR...",False
1,dev,main,nucc_taxonomy_250,"[Code, Grouping, Classification, Specializatio...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
2,dev,raw,fips,"[fipscounty, countyname_fips, state, cbsa_code...","[DOUBLE, VARCHAR, VARCHAR, DOUBLE, VARCHAR, VA...",False
3,dev,raw,nppes,"[NPI, Entity Type Code, Replacement NPI, Emplo...","[BIGINT, DOUBLE, DOUBLE, VARCHAR, VARCHAR, VAR...",False
4,dev,raw,nucc_taxonomy_250,"[Code, Grouping, Classification, Specializatio...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False

In [22]:
all_data = conn.execute("SHOW ALL TABLES").fetchdf()
all_data

,database,schema,name,column_names,column_types,temporary
0,dev,main,nppes_sammpledf,"[NPI, Entity Type Code, Replacement NPI, Emplo...","[BIGINT, DOUBLE, DOUBLE, VARCHAR, VARCHAR, VAR...",False
1,dev,main,nucc_taxonomy_250,"[Code, Grouping, Classification, Specializatio...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
2,dev,raw,fips,"[fipscounty, countyname_fips, state, cbsa_code...","[DOUBLE, VARCHAR, VARCHAR, DOUBLE, VARCHAR, VA...",False
3,dev,raw,nppes,"[NPI, Entity Type Code, Replacement NPI, Emplo...","[BIGINT, DOUBLE, DOUBLE, VARCHAR, VARCHAR, VAR...",False
4,dev,raw,nucc_taxonomy_250,"[Code, Grouping, Classification, Specializatio...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False

In [24]:
fips_df= conn.execute("SELECT * FROM raw.fips").fetchdf()
fips_df.head()

,fipscounty,countyname_fips,state,cbsa_code,cbsa_name,ssa_code,state_name,countyname_rate
0,2013.0,ALEUTIANS EAST,AK,NaN,NaN,02013,ALASKA,ALEUTIANS EAST
1,2016.0,ALEUTIANS WEST,AK,NaN,NaN,02013,ALASKA,ALEUTIANS EAST
2,2013.0,ALEUTIANS EAST,AK,NaN,NaN,02016,ALASKA,ALEUTIANS WEST
3,2016.0,ALEUTIANS WEST,AK,NaN,NaN,02016,ALASKA,ALEUTIANS WEST
4,2020.0,ANCHORAGE,AK,11260.0,"Anchorage, AK",02020,ALASKA,ANCHORAGE